export * from './emailConfirmation'
export * from './home'
export * from './login'
export * from './solicitar'
export * from './signUp'
export * from './historico'
export * from './profile'
export * from './admin'
